INSERT INTO MEMBER (NO, ID, PWD, NICK, NAME, BIRTH_DATE, ADDRESS, PHONE, EMAIL, CODE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'qwer1', 'qwer1', 'qwerN1', 'John Doe1', '19900101', '123 Street, City, Country', '12345678901', 'example1@example.com', '9999');

INSERT INTO MEMBER (NO, ID, PWD, NICK, NAME, BIRTH_DATE, ADDRESS, PHONE, EMAIL, CODE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'qwer2', 'qwer2', 'qwerN2', 'John Doe2', '19900101', '123 Street, City, Country', '12345678902', 'example2@example.com', '9999');
COMMIT;

INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '신정', TO_DATE('0101', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '삼일절', TO_DATE('0301', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '어린이날', TO_DATE('0505', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '현충일', TO_DATE('0606', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '광복절', TO_DATE('0815', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '추석', TO_DATE('0914', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '추석', TO_DATE('0915', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '추석', TO_DATE('0916', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '대체공휴일', TO_DATE('0917', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '개천절', TO_DATE('1003', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '한글날', TO_DATE('1009', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '성탄절', TO_DATE('1225', 'MMDD'));
COMMIT;

INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '설날', TO_DATE('0209', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '설날', TO_DATE('0210', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '설날', TO_DATE('0211', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '대체공휴일', TO_DATE('0212', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '대체공휴일', TO_DATE('0506', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '석가탄신일', TO_DATE('0515', 'MMDD'));
COMMIT;

INSERT INTO SCHEDULE (
    NO, 
    WRITER_NO, 
    TITLE, 
    CONTENT, 
    ENROLL_DATE, 
    MODIFY_DATE, 
    DEL_YN, 
    CHECK_DATE, 
    CODE
) VALUES (
    SEQ_SCHEDULE_NO.NEXTVAL, 
    9, 
    '데이트', 
    '여친과 데이트', 
    SYSDATE, 
    NULL, 
    'N', 
    TO_DATE('2024-06-30', 'YYYY-MM-DD'), 
    '9999'
);