DROP SEQUENCE SEQ_MEMBER_NO;

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TODO_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CALENDER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HOLIDAY_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SCHEDULE_NO NOCACHE NOCYCLE;

CREATE TABLE ADMIN (
   NO       NUMBER         CONSTRAINT PK_MEMBER_NO   PRIMARY KEY
   ,ID      VARCHAR2(20)   NOT NULL
   ,PWD     VARCHAR2(20)   NOT NULL   
   ,NICK    VARCHAR2(20)   NOT NULL   
);

CREATE TABLE MEMBER (
	NO	            NUMBER	        CONSTRAINT PK_MEMBER_NO   PRIMARY KEY
    ,ID             VARCHAR2(20)    NOT NULL CONSTRAINT UQ_MEMBER_ID UNIQUE
    ,PWD	        VARCHAR2(20)    NOT NULL
    ,NICK	        VARCHAR2(20)	NOT NULL
    ,NAME	        VARCHAR2(20)	NOT NULL
    ,BIRTH_DATE	    CHAR(8)	        NOT NULL
    ,ADDRESS	    VARCHAR2(100)	NOT NULL
    ,PHONE	        CHAR(11)	    NOT NULL
    ,EMAIL	        VARCHAR2(100)	NOT NULL
    ,EMROLL_DATE	TIMESTAMP	    DEFAULT SYSDATE
    ,MODIFY_DATE	TIMESTAMP	    
    ,QUIT_DATE	    TIMESTAMP	    
    ,QUIT_YN	    CHAR(1)	        DEFAULT 'N'  
);

CREATE TABLE TODO (
    NO	            NUMBER	CONSTRAINT PK_MEMBER_NO  PRIMARY KEY
    ,WRITER_NO	    NUMBER	NOT NULL
    ,TITLE	        VARCHAR2(100)	NOT NULL
    ,CONTENT	    VARCHAR2(4000)	NOT NULL
    ,ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE
    ,MODIFY_DATE	TIMESTAMP	
    ,COMPLETE_YN	CHAR(1)	DEFAULT 'N' 
    ,DEL_YN	        CHAR(1)	 DEFAULT 'N'  
);

CREATE TABLE CALENDER (
	 NO	        NUMBER	        CONSTRAINT PK_MEMBER_NO  PRIMARY KEY
    ,CODE	    VARCHAR2(4)	    NOT NULL
	,TITLE	    VARCHAR2(100)	NOT NULL
	,CONTENT	VARCHAR2(4000)	NOT NULL
);

CREATE TABLE HOLIDAY (
	NO	    NUMBER	        CONSTRAINT PK_MEMBER_NO  PRIMARY KEY
	,TITLE	VARCHAR2(100)	NOT NULL
	,DATE	CHAR(8)     	NOT NULL
);

CREATE TABLE SCHEDULE (
	NO	        NUMBER	        CONSTRAINT PK_MEMBER_NO  PRIMARY KEY
	,WRITER_NO	NUMBER	        NOT NULL
	,TITLE	    VARCHAR2(100)	NOT NULL
	,CONTENT	VARCHAR2(4000)	NOT NULL
	,DATE	    CHAR(12)	    NOT NULL
	,DEL_YN	    CHAR(1)	       	DEFAULT 'N'
);


