INSERT INTO MEMBER (NO, ID, PWD, NICK, NAME, BIRTH_DATE, ADDRESS, PHONE, EMAIL, CODE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'qwer1', 'qwer1', 'qwerN1', 'John Doe1', '19900101', '123 Street, City, Country', '12345678901', 'example1@example.com', '9999');

INSERT INTO MEMBER (NO, ID, PWD, NICK, NAME, BIRTH_DATE, ADDRESS, PHONE, EMAIL, CODE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'qwer2', 'qwer2', 'qwerN2', 'John Doe2', '19900101', '123 Street, City, Country', '12345678902', 'example2@example.com', '9999');
COMMIT;

INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '신정', 1, TO_DATE('0101', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '삼일절', 1, TO_DATE('0301', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '어린이날', 1, TO_DATE('0505', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '현충일', 1, TO_DATE('0606', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '광복절', 1, TO_DATE('0815', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '추석', 1, TO_DATE('0914', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '추석', 1, TO_DATE('0915', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '추석', 1, TO_DATE('0916', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '대체공휴일', 1, TO_DATE('0917', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '개천절', 1, TO_DATE('1003', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '한글날', 1, TO_DATE('1009', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '성탄절', 1, TO_DATE('1225', 'MMDD'));
COMMIT;

INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '설날', 1, TO_DATE('0209', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '설날', 1, TO_DATE('0210', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '설날', 1, TO_DATE('0211', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '대체공휴일', 1, TO_DATE('0212', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '대체공휴일', 1, TO_DATE('0506', 'MMDD'));
INSERT INTO HOLIDAY (NO, TITLE, WRITER_NO, HOLIDAY_DATE) VALUES (SEQ_HOLIDAY_NO.NEXTVAL, '석가탄신일', 1, TO_DATE('0515', 'MMDD'));
COMMIT;

INSERT INTO SCHEDULE ( NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_SCHEDULE_NO.NEXTVAL, 2, '데이트', '여친과 데이트', SYSDATE, NULL, 'N', TO_DATE('2024-06-30', 'YYYY-MM-DD'), '9999' );
INSERT INTO SCHEDULE ( NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_SCHEDULE_NO.NEXTVAL, 2, '데이트', '여친과 데이트', SYSDATE, NULL, 'N', TO_DATE('2024-06-29', 'YYYY-MM-DD'), '9999' );
INSERT INTO SCHEDULE ( NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_SCHEDULE_NO.NEXTVAL, 2, '데이트', '여친과 데이트', SYSDATE, NULL, 'N', TO_DATE('2024-06-28', 'YYYY-MM-DD'), '9999' );
COMMIT;

INSERT INTO TODO ( NO, WRITER_NO, TITLE, CONTENT, CATEGORY, ENROLL_DATE, MODIFY_DATE, COMPLETE_YN, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_TODO_NO.NEXTVAL, 1, 'TODO 제목', 'TODO 내용', 'TODO', SYSDATE, NULL, 'N', 'N', TO_DATE('2024-06-28', 'YYYY-MM-DD'), '9999' );

INSERT INTO MEMO ( NO, WRITER_NO, TITLE, CONTENT,  ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_MEMO_NO.NEXTVAL, 1, '기념일 제목1', '기념일 내용입니다1.',  SYSDATE, NULL, 'N', TO_DATE('2024-06-28', 'YYYY-MM-DD'), '9999' );


SELECT *
FROM HOLIDAY
;
SELECT *
FROM SCHEDULE
;

SELECT 
    C.NO
    ,C.CODE
    ,B.CHECK_DATE
    ,T.TITLE
    ,T.CONTENT
    ,C.DEL_YN
	FROM CALENDER C
	JOIN TODO T ON C.CODE = T.CODE
	JOIN SCHEDULE S ON T.CODE = S.CODE
	JOIN ANNIVERSARY A ON C.NO = A.NO
	JOIN ACCOUNT_BOOK B ON C.NO = B.NO
	WHERE C.CODE = '9999'
	AND C.DEL_YN =  'N'
    ;
    
SELECT
    TITLE
    , CONTENT
    , CHECK_DATE
FROM SCHEDULE
;
    
SELECT
    S.TITLE,
    S.CONTENT,
    S.CHECK_DATE
FROM SCHEDULE S
JOIN ANNIVERSARY A ON A.CODE = S.CODE
JOIN DIARY D ON D.CODE = S.CODE
JOIN TODO T ON T.CODE = S.CODE
;

SELECT S.TITLE, S.CONTENT, S.CHECK_DATE
FROM SCHEDULE S
WHERE S.CODE = '9999'

UNION ALL

SELECT A.TITLE, A.CONTENT, A.CHECK_DATE
FROM ANNIVERSARY A
WHERE A.CODE = '9999'

UNION ALL

SELECT D.TITLE, D.CONTENT, D.CHECK_DATE
FROM DIARY D
WHERE D.CODE = '9999'

UNION ALL

SELECT T.TITLE, T.CONTENT, T.CHECK_DATE
FROM TODO T
WHERE T.CODE = '9999'
;

    SELECT
        S.TITLE AS TITLE,
        S.CONTENT AS CONTENT,
        S.CHECK_DATE AS CHECK_DATE
    FROM SCHEDULE S
    JOIN ANNIVERSARY A ON A.CODE = S.CODE
    JOIN DIARY D ON D.CODE = S.CODE
    JOIN TODO T ON T.CODE = S.CODE
    WHERE S.CODE = '9999'
;

        SELECT NO, TITLE, TO_CHAR(HOLIDAY_DATE, 'YYYY-MM-DD')
        FROM HOLIDAY;


