--계정생성
INSERT INTO MEMBER (NO, ID, PWD, NICK, NAME, BIRTH_DATE, ADDRESS, PHONE, EMAIL, CODE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'qwer1', 'qwer1', 'qwerN1', 'John Doe1', '19900101', '123 Street, City, Country', '12345678901', 'example1@example.com', '9999');

INSERT INTO MEMBER (NO, ID, PWD, NICK, NAME, BIRTH_DATE, ADDRESS, PHONE, EMAIL, CODE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'qwer2', 'qwer2', 'qwerN2', 'John Doe2', '19900101', '123 Street, City, Country', '12345678902', 'example2@example.com', '9999');

--관리자계정 생성--
INSERT INTO ADMIN (NO, ID, PWD, NICK)
VALUES (SEQ_ADMIN_NO.NEXTVAL, 'admin', '1234', 'admin');
COMMIT;

--스케쥴
INSERT INTO SCHEDULE ( NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_SCHEDULE_NO.NEXTVAL, 2, '데이트', '여친과 데이트', SYSDATE, NULL, 'N', TO_DATE('2024-06-30', 'YYYY-MM-DD'), '9999' );
INSERT INTO SCHEDULE ( NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_SCHEDULE_NO.NEXTVAL, 2, '데이트', '여친과 데이트', SYSDATE, NULL, 'N', TO_DATE('2024-06-29', 'YYYY-MM-DD'), '9999' );
INSERT INTO SCHEDULE ( NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_SCHEDULE_NO.NEXTVAL, 2, '데이트', '여친과 데이트', SYSDATE, NULL, 'N', TO_DATE('2024-06-28', 'YYYY-MM-DD'), '9999' );

--TODO
INSERT INTO TODO ( NO, WRITER_NO, TITLE, CONTENT, CATEGORY, ENROLL_DATE, MODIFY_DATE, COMPLETE_YN, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_TODO_NO.NEXTVAL, 1, 'TODO 제목', 'TODO 내용', 'TODO', SYSDATE, NULL, 'N', 'N', TO_DATE('2024-06-28', 'YYYY-MM-DD'), '9999' );

--기념일
INSERT INTO ANNIVERSARY ( NO, WRITER_NO, TITLE, CONTENT, CATEGORY, ENROLL_DATE, MODIFY_DATE, DEL_YN, CHECK_DATE, CODE )
VALUES ( SEQ_ANNIVERSARY_NO.NEXTVAL, 1, '기념일 제목', '기념일 내용입니다.', 'ANNI', SYSDATE, NULL, 'N', TO_DATE('2024-06-28', 'YYYY-MM-DD'), '9999' );

--공지 작성--
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목1', '공지내용1');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목2', '공지내용2');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목3', '공지내용3');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목4', '공지내용4');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목5', '공지내용5');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목6', '공지내용6');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목7', '공지내용7');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목8', '공지내용8');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목9', '공지내용9');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목10', '공지내용10');
INSERT INTO NOTICE (NO, WRITER_NO, TITLE, CONTENT)
VALUES (SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목11', '공지내용11');

--자주묻는질문 작성--
INSERT INTO FAQ (NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE)
VALUES (SEQ_FAQ_NO.NEXTVAL, 1, '새로운 FAQ 제목', '새로운 FAQ 내용', SYSDATE);

--QNA 작성--
INSERT INTO QNA (NO,WRITER_NO, TITLE, CONTENT, ENROLL_DATE, MODIFY_DATE, DEL_YN, ADMIN_TITLE, ADMIN_CONTENT, ADMIN_ENROLL_DATE)
VALUES (SEQ_QNA_NO.NEXTVAL, 2, '새로운 QNA 제목', '새로운 QNA 내용', SYSDATE, SYSDATE, 'N', '관리자 제목', '관리자 내용', SYSDATE);

COMMIT;
